<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <Version>0.2.0</Version>
    <Company>Wslhub</Company>
    <Authors>Wslhub</Authors>
    <Product>Wslhub</Product>
    <Description>Windows Subsystem for Linux API wrapper for .NET 10 and .NET Standard 2.0.</Description>
    <Copyright>(c) WSLHub contributors</Copyright>
    <PackageProjectUrl>https://github.com/wslhub/wsl-sdk-dotnet</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/wslhub/wsl-sdk-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>WSL;SDK;Windows</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="License/License.txt" Pack="true" PackagePath="" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <InternalsVisibleTo Include="Wslhub.Sdk.UnitTests" />
  </ItemGroup>
</Project>
