<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wslhub.Sdk/Wslhub.Sdk.csproj" />
  </ItemGroup>
</Project>
